name: invariant-fuzzing-template

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.9.3

solidity: 
  import_remapping:
    - "@openzeppelin/=OpenZeppelin"

ethereum:
  default_network: mainnet-fork
  local:
    default_provider: foundry
  
foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy