[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ffi = true     # to enable vyperDeployer calling vyper compiler

# Update Slither/Mythrill config files and GH actions when you update the dependencies:
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

SALT = "${SALT}"
OWNER = "${OWNER}"
ALLOW_LIST_ADDRESSES = "${ALLOW_LIST_ADDRESSES}"
PK_ACCOUNT = "${PK_ACCOUNT}"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default.invariant]
fail_on_revert = false
runs = 2000
depth = 23