name: run-test

on:
  pull_request:
    branches: [ "*" ]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install Vyper
        run: pip install vyper==0.3.7

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Forge Dependencies
        run: |
          forge install foundry-rs/forge-std --no-commit
          forge install openzeppelin/openzeppelin-contracts --no-commit
        id: install

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
        run: |
          forge test -vvv
        id: test

      - name: Run Forge Coverage
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
        run: |
          forge coverage
        id: coverage
